### ISSUE TITLE
Idea on how to implement Nightriders

### ISSUE THREAD

**Issue by Supyovalk** [Infinite-Chess/infinitechess.org#11]
So my idea to how algorithm wise to implement Nightrider's Possible Algorithm
Assume you know the "Bounding box" of all the chess pieces.
Then for every of the 8 Knight directions, do the following persudo-algorithm:
1. Go a knight's step in the selected direction
2. If current square is outside of bounding box (only relevant to check certain edges of the Box per direction), Add "All knight moves in that direction to infinity" To Possible Moves and finish process
3. If current square is taken, Add "All Knight moves in that direction up to and not including current square" To Possible Moves and finish process
4. Return to square 1
Do you think that's a sufficient method?

**Comment by Naviary2** [comment]
Hmm. I like the idea! But what if the bounding box is 1 million squares big? That a lot of squares to check if it's legal to move to.

Me and discord member Scorpione Orzion [had a conversation](https://discord.com/channels/1114425729569017918/1115358966642393190/1115358998686867537) about implementing knightriders a while back !

Basically the way pieces are stored in the game is by rank, file, and diagonal. This way it makes it super easy to get for legal moves because we can say "Is there any other piece on this line? If so, block the selected piece's path". Our idea was to also organize the game's pieces organized by hippogonal (or knightrider lines), so we could then ask "Is there any other piece on this knightrider line? Then block".

Infinitely sliding moves are kept track of like: [-Infinity, 15], where the first number is the left limit, and right number the right. In this way, knightrider lines could be kept track of the same way, treated similar to infinite sliders, except it's an infinite slider ever (1,2) squares. Sliding moves are separated from leaping moves internally.

BUT, your idea may be useful for games with infinitely many pieces! Those games will require generation algorithms, so it's not so easy to ask "are there any other pieces on this line?". We'll only be able to calculate a finite area of legal moves at a time.

**Comment by pradyung** [comment]
I think you might be able to do something similar to storing the pieces based on hippogonal lines, but instead of actually storing them, you calculate the hippogonal line(s) when generating knightrider moves. For example, if there's a knightrider at (0,0), then for every other piece, you would check if its x-coordinate is 2x its y-coordinate (or the other way around), meaning that it would block the knight rider.

**Comment by Naviary2** [comment]
Yes, this would avoid having to organize all the pieces into their respective hippogonals, but the point of organizing them is to increase the speed of legal move calculation and the checkmate algorithm. It the difference between iterating through every single piece in the game, or only through those on the line. This actually speeds it up a ton.

**Comment by pradyung** [comment]
Wouldn't you need to iterate over every piece anyway to check which ones are on the same hippogonal? Unless I'm misunderstanding how the pieces are stored

**Comment by Naviary2** [comment]
That is only done once, at the initialization of the game. The lines then only need to be updated once every time a piece moves.

**Comment by Naviary2** [comment]
#66 This is the PR working on implementing hippogonal riders!
