### ISSUE TITLE
Unique user ID

### ISSUE THREAD

**Issue by RPink47** [Infinite-Chess/infinitechess.org#114]
Add a unique ID to every user, which will be referenced instead of the username.
This is so if user with name X deletes his account, the username X will still be available, but won't be referenced by the games played by the old user. With this system renaming could also be made.

**Comment by Naviary2** [comment]
If name changes are allowed, if someone deletes their account, then someone else create an account with the same username, how will we differentiate their games from each other? Should all ICNs (game code) contain the user ID with, or instead of, their name? This could potentially increase the size of all game code. Should we allow name changes?

**Comment by RPink47** [comment]
> ... Should all ICNs (game code) contain the user ID...

thats the idea, and in the future, name changes may be supported.

**Comment by Naviary2** [comment]
[We have discussed](https://discord.com/channels/1114425729569017918/1265042653037465714/1265359361891631104) adding the WhiteID and BlackID attributes to all ICN game code to allow the changing of usernames, and user's IDs will never change.

**Comment by Naviary2** [comment]
This has now been added. 🎉 All user data is about to be migrated to a database and each member will be given a unique user ID. Game notation also includes each players base–62 ID.

Name changes will now be supported in the future without breaking links to game history
