### ISSUE TITLE
Brute Force Login Passwords

### ISSUE THREAD

**Issue by Naviary2** [Infinite-Chess/infinitechess.org#2]
After you click "Log In" to test if your username and password is correct, there is no delay until the server lets you try again. Issue this creates:
* Hackers can attempt to brute force users passwords by spamming every single password.

## Proposal ##

Add a 1-second delay between login attempts, on a per-user basis. **But** a new issue this could create is:
* Hackers can attempt your password once a second to effectively lock you out of your account.

No other solutions thought of.

**Comment by tsevasa** [comment]
I would propose a 1-second delay cooldown per IP-address for a given user account, in order to address your concern. Still not perfect, but at least better than nothing.

**Comment by rohit12043** [comment]
What about increasing the delay after each failed login attempt? You can reset the delay after a successful login.

**Comment by Weigurde** [comment]
Something common on most platforms is that if you haven't logged into a given user account recently (say, a week), it sends an OTP to the email it was made with. This would also be useful to implement for #1 .

**Comment by Heinrich-XIAO** [comment]
Per IP login timeouts could also be used similarly to the iPhone password timeout.

**Comment by this-is-not-available** [comment]
I think something I would implement would be like a queue for login attempts. 0.5 second delay between each attempt. This has a few benefits:

1. If hackers try to log you out, they will only succeed in delaying your login attempt.
2. Multiple hacker IPs will just bottleneck each other.

**Comment by jacblo** [comment]
regarding the queue solution - 
They can use that on a bunch of different users to overload memory. Let's say a hacker sends 1000 password attempts, each attempt being a million characters long, that's at least a gigabyte of memory to store that queue. 
Since they can clearly send over 2 attempts per second, they would be raising the size of the queue to any arbitrary size, so this is feasible.

One possible solution would be to limit the password length, but that's kinda just kicking the can down the road, they'd need to run for longer with more requests but still be doable.
If you limit the amount of requests they can send per second or limit the maximum size of queue for each user, well then once again they can completely stop your login attempt as they can always keep that queue full, or just constantly send attempts at the rate limit.

I think a rate limit per IP would be the best course of action. You could also make the delay time increase as they have more failed attempts as others here proposed.

**Comment by rylid-umil** [comment]
The reason a Client-side wouldn't work is because a hacker could some how enter passwords even faster with multiple devices (example, use 4 computers at once to spam 4 passwords a second)

**Comment by this-is-not-available** [comment]
Hackers can bypass the client (website) entirely by sending a request to the server directly. This project is open source, so they know exactly what the backend looks like.

**Comment by jacblo** [comment]
Right, so all this discussion is based on the assumption that these limits are set on the server's side

**Comment by Naviary2** [comment]
#61 Would fix this

**Comment by Naviary2** [comment]
Fixed! Thanks to @shacharrr
