### ISSUE TITLE
Implement ability to offer a draw

### ISSUE THREAD

**Issue by this-is-not-available** [Infinite-Chess/infinitechess.org#9]
Currently, offering a draw just kind of does nothing:
`case 'offerdraw':
                console.error("Don't know how to offer draw yet.")`

So, someday someone needs to implement this.

It's not a bug fix and also not a database migration, 
but somewhere in the middle, where it will take somewhere around 1 to 3 days.

**Comment by Naviary2** [comment]
Yes! This will be nice! I've been thinking the UI needs an update. The main menu (or return to lobby) button should be along the bottom of the screen instead of hidden within the pause menu. The offer draw button should be close to that. Players usernames should hyperlink to their profile, and display their elo, etc!

This will be tagged as an "enhancement" (or feature request)!

**Comment by MGGSK** [comment]
Also don't allow players to spam draw offers.

**Comment by this-is-not-available** [comment]
Discord discussion here
https://discord.com/channels/1114425729569017918/1260309465362731048

**Comment by Naviary2** [comment]
#39 Here's the linked PR adding this

**Comment by this-is-not-available** [comment]
Yes that's my work right there

**Comment by this-is-not-available** [comment]
Bruh we didn't close this. Now it is closed
